---
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "29.1"
          elixir-version: "1.20.0"
          version-type: strict

      - name: Lint
        run: elixir scripts/lint.exs

      - name: Test
        run: elixir test/sieve_test.exs
